development:
  adapter: postgresql
  database: permit_development
  username: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: permit_test
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: permit_production
  username: permitpal